-- SUB QURIES
USE CODEGNAN;
CREATE TABLE EMPLOYEESSS(
	EMPLOYEE_ID INT,
    EMPLOYEE_NAME VARCHAR(100),
    SALARY INT
);
INSERT INTO EMPLOYEESSS VALUES (101,"A",10000),(102,"B",20000),(103,"C",30000);
SELECT * FROM EMPLOYEESSS;

-- SCALAR SUB QUERY
SELECT 
	EMPLOYEE_ID,
    SALARY,
    (SELECT AVG(SALARY) FROM EMPLOYEESSS) AS AVG_SALARY 
FROM EMPLOYEESSS;

-- SINGLE ROW SUBQUERY

SELECT
	EMPLOYEE_ID,
    EMPLOYEE_NAME,
    SALARY
FROM 
	EMPLOYEESSS
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEESSS);

-- MULTI ROW SUB QUERY
CREATE TABLE EMPDETAILS1(
	EMP_ID INT,
    DEPT_ID INT,
    EMP_NAME VARCHAR(100),
    SALARY INT
);
INSERT INTO EMPDETAILS1 VALUES (101,1,"A",10000),(102,2,"B",20000),(103,1,"AA",15000),(104,2,"BB",25000);
CREATE TABLE DEPARTMENT1(
	DEPT_ID INT,
    LOC_ID INT
);
INSERT INTO DEPARTMENT1 VALUES (1,1004),(2,1004),(1,1005),(2,1006);
SELECT
	EMP_ID,
    EMP_NAME,
    SALARY
FROM
	EMPDETAILS1
WHERE
	DEPT_ID IN (SELECT DEPT_ID FROM DEPARTMENT1 WHERE LOC_ID = 1006);

-- MULTIPLE COLUMN SUB QUERY