USE CODEGNAN;

CREATE TABLE TABLE1(
	FNAME VARCHAR(100),
    LNAME VARCHAR(100),
    EMAIL VARCHAR(100),
    MOBILE VARCHAR(100)
);

INSERT INTO TABLE1 VALUES ("SAI","VARDHAN","SAI@GMAIL.COM","789-357-0611"),("SAI","vivek","VIVEK@gmail.con","987-654-3211");
INSERT INTO TABLE1 VALUES ("vishnu","VARDHAN","vishnu@GMAIL.com","7893570611"),("vinay","vivek","VInay@gmail.con","987-654-3211");
INSERT INTO TABLE1 VALUES ("A","B","ABC@EMAIL.COM","123456");

SELECT * FROM TABLE1;

#CONCAT
SELECT CONCAT("SAI"," ","VARDHAN") AS NAME;
SELECT *,CONCAT(FNAME,"    ",LNAME) AS FULLNAME FROM TABLE1;
#CONCAT_WS
SELECT *,CONCAT_WS("     ",FNAME,LNAME,EMAIL,MOBILE) AS DETAILS FROM TABLE1;
SELECT CONCAT_WS(" , ","APPLE","BANANA","CHERRY","DONKEY") AS VALUESS;
#LOWER
SELECT LOWER("SAi") as lowerr;
SELECT *,LOWER(EMAIL) AS DEFINEDEMAIL FROM TABLE1;
#UPPER
SELECT UPPER("varDHan") AS UPPERR;
SELECT *,UPPER(EMAIL) AS DEFINEDEMAIL FROM TABLE1;
#REVERSE
SELECT REVERSE("APPLE") AS REVERSEE;
SELECT *,REVERSE(MOBILE) AS REVERSED FROM TABLE1;
#REPLACE
SELECT REPLACE("HELLO","LL","T") AS REPLCEEE;
SELECT *,REPLACE(MOBILE,"-","") AS RESULTMOBILE FROM TABLE1;
#LENGTH
SELECT LENGTH("SAI VARDHAN") AS LENGTHH;
SELECT *,LENGTH(EMAIL) AS EMAILLENGTH FROM TABLE1;
#CHAR_LENGTH
SELECT CHAR_LENGTH("SAI VARDHAN") AS CHARLENGTH;
SELECT *,CHAR_LENGTH(EMAIL) AS EMAILLENGTH FROM TABLE1;
#SUBSTRING
SELECT SUBSTRING("ABCDEFGHIJKL",3) AS DFGHJ;
SELECT SUBSTRING("ABCDEFGHIJKL",3,4) AS DFGHJ;
SELECT *,SUBSTRING(MOBILE,1,3) AS THREEDIGITS FROM TABLE1;

#LIKE
SELECT * FROM TABLE1 WHERE MOBILE LIKE "___-___-____";
SELECT * FROM TABLE1 WHERE EMAIL LIKE "%@GMAIL.COM";






