use codegnan;

#PRIMARY KEY
#FOREIGN KEY
#UNIQUE
#NOT NULL
#CHECK
#DEFAULT
CREATE TABLE PMKEY(
	C1 INT PRIMARY KEY,
    C2 VARCHAR(10) UNIQUE,
    C3 VARCHAR(12) NOT NULL,
    C4 INT CHECK (C4>18),
    C5 INT DEFAULT 0
);
CREATE TABLE FKEY(
	C11 INT PRIMARY KEY,
    C22 VARCHAR(10),
    C33 FLOAT DEFAULT 10.34,
    C44 INT NOT NULL DEFAULT 100,
    FOREIGN KEY (C22) REFERENCES PMKEY(C2)
);

CREATE TABLE ALTERCMD(
	SID INT
);
#ADDING COLUMN
ALTER TABLE ALTERCMD ADD SNAME VARCHAR(10);
ALTER TABLE ALTERCMD ADD (C1 INT,C2 INT);
#DELETING COLUMN
ALTER TABLE ALTERCMD DROP COLUMN C1;
#MODIFY
ALTER TABLE ALTERCMD MODIFY COLUMN C2 DATE;
#ADD CONSTRAINT
ALTER TABLE ALTERCMD ADD CONSTRAINT PRIMARY KEY(SID);
#RENAME COLUMN NAME
ALTER TABLE ALTERCMD RENAME COLUMN SID TO STUID;
DESCRIBE ALTERCMD;
 
#DELETING TABLE ALTERCMD;
DROP TABLE ALTERCMD;
DESCRIBE ALTERCMD;

#DELETING DATABASE
DROP DATABASE CODEGNAN_DB;






