#PROBLEM - 1
SELECT CASE
	WHEN (A+B)<C OR (A+C)<B OR (B+C)< A THEN "NOT A TRAINGLE"
    WHEN A=B AND B=C AND C=A THEN "EQUALATERAL"
    WHEN A=B OR B=C OR C=A THEN "ISOCELES"
    ELSE "SCALENE"
	END AS TYPE_OF_TRIANGLE
FROM TRAINGLES;

#PROBLEM - 2
SELECT NAME FROM EMPLOYEES WHERE (PRODUCTS*PRICE)=TOTALMONEY;

#PROBLEM - 3
SELECT NAME FROM EMPLOYEES WHERE SALARY>2000 AND MONTHS < 10;

#PROBLEM - 4
SELECT * FROM STATION WHERE NOT CITY LIKE ["A","E","I","O","U"]%["A","E","I","O","U"];

#PROBLEM - 5
SELECT * FROM EMPLOYEES WHERE EMAIL LIKE "%@GMAIL.COM" AND MOBILE LIKE "____-____-__" AND NAME LIKE "S%";

#PROBLEM - 6
SELECT * FROM TRAINGLES WHERE A+B>C AND B+C>A AND A+C>B;

#PROBLEM - 7
SELECT * FROM USERS WHERE UPPER(FIRSTNAME) = FIRSTNAME AND LOWER(LASTNAME)=LASTNAME;

#PROBLEM - 8
SELECT *,CONCAT(LASTNAME,".",FIRSTNAME,"@CODEGNAN.COM") FROM DETAILS;














